### ISSUE TITLE
Support for Opaque ADTs

### ISSUE THREAD

**Issue by anthonyjoeseph** [sledorze/morphic-ts#104]
I would like to be able to make my ADT types opaque

[This technique](https://codemix.com/opaque-types-in-javascript) works but it is clunky

```tsx
type Vehicle = ADTType<typeof Vehicle> & { _: Vehicle }
const bike: Vehicle = Vehicle.of.Bicycle({ color: 'blue' }) as Vehicle
```

I would like an `OpaqueADTType` type alias and `ofOpaque` and `asOpaque` methods

**Comment by sledorze** [comment]
Like depicted here:
https://github.com/sledorze/morphic-ts#want-opaque-nominal-instead-of-structural-inferred-types

You can apply use that pattern:

```typescript
export const Bicycle_ = summon(F =>
  F.interface(
    {
      type: F.stringLiteral('Bicycle'),
      color: F.string()
    },
    'Bicycle'
  )
)
export interface Bicycle extends AType<typeof Bicycle_> {}
export interface BicycleRaw extends EType<typeof Bicycle_> {}
export const Bicycle = AsOpaque<BicycleRaw, Bicycle>()(Bicycle_)

export const Car_ = summon(F =>
  F.interface(
    {
      type: F.stringLiteral('Car'),
      kind: F.keysOf({ electric: null, fuel: null, gaz: null }),
      power: F.number()
    },
    'Car'
  )
)
export interface Car extends AType<typeof Car_> {}
export interface CarRaw extends EType<typeof Car_> {}
export const Car = AsOpaque<CarRaw, Car>()(Car_)

export const Vehicle = tagged('type')({ Car, Bicycle })
export type Vehicle = AOfMorhpADT<typeof Vehicle>
```

To ease the pain, use the Snippets defined in the repo (it becomes pretty fast experience).
https://github.com/sledorze/morphic-ts/blob/master/.vscode/snippets.code-snippets

**Comment by anthonyjoeseph** [comment]
Thanks for such a speedy response! I'm embarrassed that I didn't see this on the README.

From now on I'll use 'summon' instead of 'makeADT'

**Comment by anthonyjoeseph** [comment]
In case anyone else is reading this, the above solution will only make members of an ADT opaque. To make the ADT itself opaque, you can use [`newtype-ts`](https://github.com/gcanti/newtype-ts)

```ts
export const VehicleADT = makeADT('type')({
	Car: ofType<Car>(),
	Motorbike: ofType<Motorbike>(),
	Bicycle: ofType<Bicycle>()
});
export type VehicleADT = ADTType<typeof VehicleADT>
export interface Vehicle extends Newtype<{ readonly Vehicle: unique symbol }, VehicleADT> {}
export const Vehicle = iso<Vehicle>()

const bike = VehicleADT.as.Bicycle({ color: 'blue' })
const opaqueBike = Vehicle.wrap(bike);
// const bike: { type: "Bicycle"; }
// const opaqueBike: Vehicle
```

Snippet:

https://gist.github.com/anthonyjoeseph/38a778383a58c9f13b669b90b6519b0e
