### ISSUE TITLE
LenseFromProp typo?

### ISSUE THREAD

**Issue by anthonyjoeseph** [sledorze/morphic-ts#111]
Unless there's another meaning that I don't know, I think ['LenseFromProp'](https://github.com/sledorze/morphic-ts#optics-via-monocle) is a typo for 'LensFromProp' (which is how it is spelled in [monocle-ts](https://github.com/gcanti/monocle-ts/blob/e32cd0accb6a4b0ad241ab88ce87aac9dc46cc58/test/Lens.ts#L48)).

It caused me a small amount of confusion at first.

It's a misspelling according to [wikipedia](https://en.wikipedia.org/wiki/Lense).

Same for ['LenseFromProps'](https://github.com/sledorze/morphic-ts/blob/6770c70a815c8582941cde0248faf6597797669e/packages/morphic-adt/src/monocle.ts#L41) and ['LenseFromPath'](https://github.com/sledorze/morphic-ts/blob/6770c70a815c8582941cde0248faf6597797669e/packages/morphic-adt/src/monocle.ts#L42).

They're great functions though! Super useful.

**Comment by sledorze** [comment]
🤦

**Comment by anthonyjoeseph** [comment]
Thank you!
