### ISSUE TITLE
Type "smart constructor" and/or validation example?

### ISSUE THREAD

**Issue by chrischen** [sledorze/morphic-ts#124]
Is this library meant to be used in conjunction with io-ts for validation and "smart constructors" (opaque types using a constructor)?

**Comment by sledorze** [comment]
Maybe looking at this would help:

https://github.com/sledorze/morphic-ts/blob/master/packages/morphic-io-ts-interpreters/test/io-ts-interpreter.spec.ts

**Comment by sledorze** [comment]
@chrischen Closing as responded
