### ISSUE TITLE
How to use custom io-ts codecs?

### ISSUE THREAD

**Issue by chrischen** [sledorze/morphic-ts#128]
I see in the unit tests I can define the validate function, but how would I build a custom encoder?

For example, if I were implementing the Date type, its input is string, and its output (decode) would be a Date object. The encode would take Date and return a string.

**Comment by sledorze** [comment]
@chrischen this is an io-ts question actually..

You may check here as an example
https://github.com/gcanti/io-ts-types/blob/master/src/DateFromISOString.ts

**Comment by chrischen** [comment]
Hi, sorry I should have been more clear. I know how to make custom types with io-ts, but my question is how it would be used with morphic. It seems that morphic always needs a base type, so for a custom type such as say input string to output date, how do I use it with `summon`?

**Comment by frabbit** [comment]
@sledorze I have the same question, is there an example somewhere?

**Comment by ssledorze** [comment]
You may check:

https://github.com/sledorze/morphic-ts/blob/master/packages/morphic-io-ts-interpreters/test/io-ts-interpreter.spec.ts#L97

**Comment by sukazavr** [comment]
@ssledorze hello!
Could you please explain me how to wrap `NumberFromString` from `io-ts-types` with `F.newtype` to make a `number` type from `string`?

Unfortunately I couldn't figure out the application of the code from your reference:
```
interface NT extends Newtype<{ readonly NT: unique symbol }, string> {}
const NT = summon(F => F.newtype<NT>('NT')(F.string()))
```

It seems it doesn't contain any type conversion logic and I have no idea where to put it.

**Comment by ssledorze** [comment]
@sukazavr  That's not possible to use NumberFromString with an Output type of type 'string'

So you would need something like:
```typescript

// define a custom `NumberFromString`
export interface NumberFromStringC extends t.Type<number, number, unknown> {} // Output type is 'number' here

export const NumberFromString: NumberFromStringC = new t.Type<number, number, unknown>(
  'NumberFromString',
  t.number.is,
  NumberFromString_.validate,
  identity
)

export const NumberFromNumberOrString = t.union([t.number, NumberFromString])

...
// Usage
const NumberFromString = summon(F => F.number({ IoTsURI: _ => NumberFromString })) // type is M<AppEnv, number, number> (and not M<AppEnv, string, number>)
```

Or you may relax the `O`(output type) as `unknown` by using the unknownE combinator, enabling the usage of io-ts-types `NumberFromString`

```typescript
export const NumberFromString = summon(F =>
  F.unknownE(F.number(), { IoTsURI: _ => iotstypes.NumberFromString })
) // type is M<AppEnv, unknown, number>
```

Hope it helps..

**Comment by sukazavr** [comment]
@ssledorze thanks for you help!
I asked [the same Q](https://stackoverflow.com/questions/68963011/how-to-inject-io-ts-types-in-morphic-ts-summoner) on and I received one very informative answer. How do you feel about it, is it decent solution from your perspective?
https://stackoverflow.com/a/68970813/10744049

**Comment by sledorze** [comment]
@sukazavr this really shows the responder has dived into the library.
However, it is not playing the final tagless abstraction and dispatching on interpreters inside the definition which is unsafe.
I won't recommand going that path..
