### ISSUE TITLE
Make typescript a peer dependency in package.json

### ISSUE THREAD

**Issue by anthonyjoeseph** [sledorze/morphic-ts#129]
Is there a reason that `"typescript": "^3.9.3"` is a `devDependency` and not a `peerDependency`? It causes a confusing error when adding `@morphic-ts/x` to projects that use an older version of typescript (e.g. the current version of [create-react-app](https://create-react-app.dev/docs/adding-typescript/), which uses typescript 3.7.3 at the time of writing)

```
TypeScript error in /Users/anthonygabriele/Developer/repos/examples/my-app/node_modules/@morphic-ts/adt/lib/ctors.d.ts(1,13):
'=' expected.  TS1005

  > 1 | import type { Remove, ExtractUnion } from './utils';
      |             ^
    2 | import type { KeysDefinition, Tagged } from '.';
    3 | /**
    4 |  *  @since 0.0.1
```

I believe this could be avoided if `typescript` was a `peerDependency` instead of a `devDependency`

**Comment by anthonyjoeseph** [comment]
wait I think i am wrong

**Comment by anthonyjoeseph** [comment]
updated

**Comment by ssledorze** [comment]
devDependencies are not included in releases.
This is not the reason of your problem..
I guess the reason might be that `import type` is not valid for typescript 3.7.3 ...

**Comment by anthonyjoeseph** [comment]
Adding typescript as a peer dependency would at least give an [`incorrect peer dependency`](https://stackoverflow.com/a/57911670/615493) error when `@morphic-ts/x` is first installed, to give the user a clue that they need to update their typescript version

It's a small point and I understand if you don't think it's worth the change, I just thought that this error could scare off potential new users and this fix could make it easier to resolve

**Comment by ssledorze** [comment]
@anthonyjoeseph peerDependencies are for runtime.
Requiring typescript as a peer deps would be understood as 'you need typescript installed for using this library at runtime'.

**Comment by anthonyjoeseph** [comment]
I didn't realize that. Thank you for clarifying
