### ISSUE TITLE
where is the record type?

### ISSUE THREAD

**Issue by mohaalak** [sledorze/morphic-ts#137]
there is a `strMap` but I want to create a type from `keysOf` another type.

something like this

```typescript
const Language = summon(F => F.keysOf({en: null, es: null, sv:null}));

// there is no record
const TranslationText = summon(F => F.record(Language(F), F.string()));
```

**Comment by sledorze** [comment]
Sorry for the delay @mohaalak, this does not exist (yet)
If you want to provide a PR, I would be glad to review it
