### ISSUE TITLE
createReducer w/ default type inference is broken

### ISSUE THREAD

**Issue by anthonyjoeseph** [sledorze/morphic-ts#139]
this is legal:

```ts
const Vehicle = makeADT('type')({
  Car: ofType<Car>(),
  Motorbike: ofType<Motorbike>(),
  Bicycle: ofType<Bicycle>(),
});
type Vehicle = ADTType<typeof Vehicle>;
Vehicle.createReducer(55)(
  {
    Car: (a: Car) => (b: number) => 43,
    anything: (a: Motorbike) => (b: number) => 43,
    i: (a: Bicycle) => (b: number) => 43,
    want: (a: boolean) => (b: string) => 43,
  },
  (a: Vehicle) => (b: number) => 4,
)
```

typescript version 4.0.3, @morphic-ts/adt version 2.0.0-alpha.8

Also, the createReducer docs in the README show the wrong default syntax.

Maybe this should be a separate issue, but I'd personally like `createReducer` to automatically have default behavior of not changing the state, and a separate `createReducerStrict` that enforces every case to be handled.

Since redux is often practically useless w/o an async middleware, a default behavior of not changing state is common (I think)

I can make PRs if these things sound reasonable

**Comment by sledorze** [comment]
This is legal, yes, it's not `wrong` (won't execute bad code) but undesirable, indeed.
Inference encoding is a bit tricky with the matcher; I've not tried to prevent those yet; have you already succeed?

About having createReducer with a default behaviour, I would favour `createPartialReducer` as the name and would be happy to review a PR, but like you said, let's do that as part of a separate issue.

**Comment by anthonyjoeseph** [comment]
Oh ok I didn't realize that it won't execute bad code. No I haven't tried yet, I'll give it a shot though, hope it's possible!

Separate issue: https://github.com/sledorze/morphic-ts/issues/140

**Comment by sledorze** [comment]
@anthonyjoeseph  please to not keep it dandling, assign it to yourself or close it, thanks :)

**Comment by sledorze** [comment]
closing it as the issue looks like not actionnable ATM and the behaviour is actually safe
