### ISSUE TITLE
Adding factory-ts

### ISSUE THREAD

**Issue by jessekelly881** [sledorze/morphic-ts#147]
Hi all! This isn't really an issue. More, I had an idea, and I'm wondering if anyone else is interested in this. I have been using morphic-ts for a while now and just ran across factory-ts. Using factory-ts with morphic-ts is admittedly very easy, but I think it could be easier if it was included in morphic-ts core. 

Right now the code looks like this:

export const PersonM = summon(F =>
  F.interface(
    {
      name: F.string(),
      age: F.number()
    },
    'Person'
  )
)

type Person = t.TypeOf<typeof PersonM.type>

const personFactory = Factory.Sync.makeFactory<Person>({
  name: Factory.each(i => name.fullName()),
  age: Factory.each(i => 20 + (i % 10))
});

but having PersonM.factory would be more convenient. 

 https://github.com/willryan/factory.ts

**Comment by ssledorze** [comment]
Hi Jesse,
Morphic relies on fast-check for the generation of test datas
I'm not leaning toward supporting more ATM (fast-check does this job pretty
well actually)

**Comment by jessekelly881** [comment]
Ah. My mistake. I wasn't familiar with what fast-check was. After having done a bit of research I can see that fast-check is clearly a better solution than trying to use factory.ts. Closing issue.
