### ISSUE TITLE
@morphic-ts/adt - makeADT purely from type

### ISSUE THREAD

**Issue by akomm** [sledorze/morphic-ts#164]
I'm using ts-adt to create types, including sum-types. I see there are some no-op functions for typng (due to TS limitations) and I realized its a nice lib, but it seems not very convenient to use if you have already types created and only need the runtime part.

Is it possible to create a factory which works purelly on type:

```ts
const a = makeADT<SumType, '_type'>()
```
I understand that there is no information for runtime code there what keys exist, but is it possible to solve it via proxy maybe? The proxy would handle anything, the typing would restrict to domain boundaries. What do you think?

**Comment by sledorze** [comment]
Thanks for the suggestion @akomm 
I won't consider this as it would add noticeable runtime penalty for marginal boilerplate savings.
I think you may find a way to help yourself with some helper function..
