### ISSUE TITLE
Using Morphic To Implement Domain Driven Backend Architecture

### ISSUE THREAD

**Issue by danielyogel** [sledorze/morphic-ts#178]
I was wondering if anyone tried to use Morphic to create a granular/domain-driven way of backend architecture.
Something a bit like GraphQL - where you add a resolver per entity (entity may be a field or a larger entity), then the they add to each other to create the final endpoints.  
I find this more domain driven and DRY than regular way I usually see REST endpoints implemented.

For example, in my backend (tRPC/Zod, Prisma ORM) - each time I add a new field to the backend - I have to add it separately to:
1. Zod's schema (Query and mutation)
2. Prisma's "include" code (Query and mutation)
3. Prisma's "update" code (mutation)
4. Sometimes to more places in code that handle authorization and side-effects (emails and etc), and are related to the same schema from before.

In a more domain-driven approach, I would add all of those in one place that describe the field, then some framework (that may use Morphic) - would build the final queries/mutations (while not losing type-safety).

Even if no framework is used, I would like to just declare the schema once - then derive Zod & Prisma & Side-effects code.

Any comment is welcome!

**Comment by sledorze** [comment]
@danielyogel 
A lot of people had the idea but none has done it yet.
Note that Morphic is final encoding and it may be more adapted to use a initial encoding solution (as Schema from effect-ts)

**Comment by danielyogel** [comment]
@sledorze 
I think this is very interesting, and may be very useful and practical to many backend developers.

Not sure what this thing should do, or more importantly what it should not :)
If you're interested too, we can open a repo and start first with just design, before implementation. BTW, I've build a similar frontend only library, which is quite useful already.

**Comment by sledorze** [comment]
I'm currently using the effect-ts ecosystem (with a Morphic fork adapted to their different - compared to fp-ts - Std)
you may join that ecosystem, maybe you'll find some shared interests.. :)
