### ISSUE TITLE
Feature Request: createReducer without initial state

### ISSUE THREAD

**Issue by tmueller** [sledorze/morphic-ts#182]
Hi Stéphane,

thanks for creating such a fantastic library. 

I have a small feature request for `createReducer`. Would you be willing to include a `createReducer` function without initial state. 

Use cases here are `Array.prototype.reduce` or elmish update functions, which both need an intial state. But this initial state is independant of the reducer.

Regards,
Thomas

**Comment by sledorze** [comment]
Sorry, I'm not very active on this library anymore (switching from fp-ts to effect-ts made me use the Morphic port inside effect-ts).
You may use a simpler matcher I guess..
