### ISSUE TITLE
Move StateEither to either fp-ts or fp-ts-contrib

### ISSUE THREAD

**Issue by sledorze** [sledorze/morphic-ts#4]
We've derived a `StateEither` implementation (from a richer one).

https://github.com/sledorze/morphic-ts/blob/master/src/json-schema-interpreters/StateEither.ts

It's now time to move it to a better place where it can be used by others.
That move would involve writing (or adapting existing) tests.

**Comment by haredev** [comment]
@sledorze Please check PR above :)

**Comment by sledorze** [comment]
thanks @haredev
