### ISSUE TITLE
Questions..

### ISSUE THREAD

**Issue by patroza** [sledorze/morphic-ts#65]
Hey guys,

so far, I like this project, I think at least..
but so far, it is unclear to me how to constrain the primitives to something interesting, like a min or max length string, a string that looks like an email address, a password with particular requirements, an integer that must fall between two ranges.. 
I look at io-ts, and think, this type must be representable in morphic-ts - right - but, how?

am I overlooking something - Is there some sample around that satisfies these requirements, or am I just too early to the game?

I suppose a GitHub issue is not the place to ask, but then - where is?
Thank you for your time my fellow FP in TS journeymen.

**Comment by sledorze** [comment]
Hi!

You may use interpreters specific configs:
https://github.com/sledorze/morphic-ts#configurable

Here's an exemple with iotsConfig (which expose a function enabling you to override the given generated io-ts instance with one of your choice (can be custom) as long as it matches the type signature):
https://github.com/sledorze/morphic-ts/blob/master/packages/morphic-io-ts-interpreters/test/io-ts-interpreter.spec.ts#L81

**Comment by patroza** [comment]
hi @sledorze thanks a lot for your response!
I was apparently looking for `F.refinement` instead as I would like to brand.

However that does get me stuck then with the `iotsConfig`:

```typescript
const Pax2 = summon((F) => {
  const PaxNumber2 = F.refined(
    F.number(),
    (n): n is t.Branded<PositiveInt, PaxNumberBrand> => n >= 0 && n <= 6,
    "PaxNumber",
    // iotsConfig((x) =>
    //   withMessage(x, (value) => {
    //     if (!PositiveInt.is(value)) {
    //       return "Invalid input"
    //     }
    //     return `requires between 0 and max 6, but ${value} was specified.`
    //   }),
    // ),
  )
  return F.interface(
    {
      adults: PaxNumber2,
      babies: PaxNumber2,
      children: PaxNumber2,
      infants: PaxNumber2,
      teenagers: PaxNumber2,
    },
    "Pax",
  )
})
```

running with:
```
console.log(
  Pax2.type.decode({ adults: 7, babies: 1, children: 1, infants: 0, teenagers: 2 })
)
```

Uncommenting it leads to a type error (x has any type, an function return should be undefined), but ignoring the error, compiles and runs, the message is however not visible.

Thanks!

**Comment by patroza** [comment]
Alright, the trick is `F.newType`

```
const Pax2 = summon((F) => {
  type PaxNumber2 = Newtype<{ readonly PaxNumber2: unique symbol }, number>
  const PaxNumber2 = F.newtype<PaxNumber2>("PaxNumber2")(
    F.refined(
      F.number(),
      (n): n is t.Branded<PositiveInt, PaxNumberBrand> => n >= 0 && n <= 6,
      "PaxNumber",
    ),
    iotsConfig((x) =>
      withMessage(x, (value) => {
        if (!PositiveInt.is(value)) {
          return "Invalid input"
        }
        return `requires between 0 and max 6, but ${value} was specified.`
      }),
    ),
  )

  return F.interface(
    {
      adults: PaxNumber2,
      babies: PaxNumber2,
      children: PaxNumber2,
      infants: PaxNumber2,
      teenagers: PaxNumber2,
    },
    "Pax",
  )
})
```

**Comment by patroza** [comment]
Although that seems more like a workaround, is there a way to apply the `iotsConfig` to `refined` without a new type?

**Comment by patroza** [comment]
lastly, I'm confused as to how to use summoned model A, in model B:
```
const ModelA = summon((F) => F.Interface(...))
const ModelB = summon((F) => F.Interface({ x: ModelA }))
```

**Comment by sledorze** [comment]
Hi, I'll check the previous question, for the lat one, do:

```typescript
const ModelA = summon(F => F.interface({}, 'ModelA'))
const ModelB = summon(F => F.interface({ x: ModelA(F) }, 'ModelB'))
```

**Comment by sledorze** [comment]
Config is missing in refined; I'll consider this

**Comment by sledorze** [comment]
Will do a release

**Comment by sledorze** [comment]
@patroza released @morphic-ts/batteries 0.12.0

**Comment by patroza** [comment]
@sledorze very nice! Works like a dream.
Thanks for the assist and quick resolution!

**Comment by sledorze** [comment]
You're welcome, I hope the lib will be useful to you.
