### ISSUE TITLE
Logo and banner

### ISSUE THREAD

**Issue by Eldow** [sledorze/morphic-ts#78]
![morphic-banner](https://user-images.githubusercontent.com/14909656/79638856-1c62e500-8188-11ea-92ef-226a3de5c5ea.png)

Hello there ! 

Not a real big issue but morphic-ts is too amazing to lack a custom logo.

[SVG file](https://gist.github.com/Eldow/25203c148f8a9604fcb774807ae540ce#file-morphic-ts-svg)

What do you think of it ? 

Raw SVG Code :
``` 
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
<path d="M7.9,53.4C6.5,53.2,5.5,44,8,35.2c1.1-3.8,3.5-11.9,7.7-13C23.2,20,27,43.8,36.4,45.3c13.1,2,19.9-41,33.3-40.5
	c11.6,0.4,20.9,31.1,23.1,52.8c1.8,17.4-0.3,36.9-4,37.6C82.8,96.4,78.4,48.1,64,45.9c-10.3-1.6-15.9,22.5-26.8,19.9
	C25.6,63,21.6,36,15.2,37.2C10.5,38.1,9.7,53.7,7.9,53.4z"/>
</svg>
```

**Comment by sledorze** [comment]
Current officially proposed Logos:

<img width="800" alt="Screenshot 2020-05-21 at 12 43 38" src="https://user-images.githubusercontent.com/416760/82603301-b2889180-9bb2-11ea-8c38-c8b14a9ee184.png">
<img width="801" alt="Screenshot 2020-05-21 at 12 44 30" src="https://user-images.githubusercontent.com/416760/82603304-b4525500-9bb2-11ea-87b1-61e349613778.png">
<img width="799" alt="Screenshot 2020-05-21 at 12 45 03" src="https://user-images.githubusercontent.com/416760/82603305-b4eaeb80-9bb2-11ea-93c8-c3348abf28f1.png">

**Comment by Eldow** [comment]
Ok, those are looking way more professional. Happy to have participated to the exercise nevertheless !
