### ISSUE TITLE
Fast-check should be loaded only for tests

### ISSUE THREAD

**Issue by Stouffi** [sledorze/morphic-ts#8]
**Do you want to request a _feature_ or report a _bug_?**
Feature
**What is the current behavior?**
Fast-check is always loaded when bundling an app.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

**What is the expected behavior?**
From my experience, fast-check is only desirable during tests and should not be loaded as part of an app bundle.
**Which versions of morphic-ts, and which browser and OS are affected by this issue? Did this work in previous versions of morphic-ts?**

**Comment by sledorze** [comment]
I can only think of a solution where we define an Interpreter for run time and, in test, reinterpret the Morphs with a fastcheck interpreter.

This would solve that problem.

The downside being that, in tests, there's the overhead of writing the explicit derivation.

**Comment by sledorze** [comment]
@Stouffi I've introduced a specific Interpreter (ESBST) and example ( https://github.com/sledorze/morphic-ts/blob/master/packages/morphic-batteries/test/usage.spec.ts#L118-L129 )
